# -*- coding: utf-8 -*-
"""graph_builder_nodes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y3raSu3K3jQ6pXx0vZuOe0zstYLs_CYT
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import os
# %pip install osmnx networkx

import networkx as nx
import matplotlib.pyplot as plt
import json
import osmnx as ox
import matplotlib.patches as mpatches

G=ox.graph_from_place("Udupi, Karnataka, India",network_type="drive")

class Counter:
    count = 0
    def __init__(self):
        Counter.count += 1

simulation_nodes = [
    {"id": 1, "name": "DEPOT-B", "description": "Kundapur Sub Depot", "lat": 13.6316, "lon": 74.6900},
    {"id": 2, "name": "DEPOT-C", "description": "Karkala Relief Base", "lat": 13.2143, "lon": 74.9923},
    {"id": 3, "name": "NODE-S1", "description": "Padubidri Coastal Camp", "lat": 13.1345, "lon": 74.7732},
    {"id": 4, "name": "NODE-S2", "description": "Brahmavar Relief Point", "lat": 13.2518, "lon": 74.7460},
    {"id": 5, "name": "NODE-D1", "description": "Trasi Fishing Hamlet", "lat": 13.5670, "lon": 74.6925},
    {"id": 6, "name": "NODE-D2", "description": "Gangolli Coast", "lat": 13.6500, "lon": 74.6700},
    {"id": 7, "name": "NODE-D3", "description": "Byndoor Interior", "lat": 13.8667, "lon": 74.6333}
]

graph = {}

def snap_node_to_graph(lat, lon, name, G):
    node = ox.distance.nearest_nodes(G, lon, lat, return_dist=False)
    return node

for node in simulation_nodes:
    graph_node_id = snap_node_to_graph(node["lat"], node["lon"], node["name"], G)
    graph[node["id"]] = {"name": node["name"], "graph_node": graph_node_id}
    print(f"Node {node['id']:>2} | {node['name']:<25} -> OSM node {graph_node_id}")

# Tag and save once after all nodes are snapped
for sim_id, info in graph.items():
    nid = info["graph_node"]
    G.nodes[nid]["simulation_id"] = sim_id
    G.nodes[nid]["simulation_name"] = info["name"]


print("GraphML saved with simulation node names.")

nodes = {}
for node in simulation_nodes:
    graph_node_id = snap_node_to_graph(node["lat"], node["lon"],node["name"],G)
    nodes[node["id"]] = {"name": node["name"], "graph_node": graph_node_id}
    print(f"Node {node['id']:>2} | {node['name']:<25} -> OSM node {graph_node_id}")

#nodes={}
#for i in range(1,11):
#  nodes[i]={"node_id":snap_node_to_graph(simulation_nodes[i-1]["lat"],simulation_nodes[i-1]["lon"],G)}
#nodes

nods, EDGES = ox.graph_to_gdfs(G)

EDGES

def plot_nodes_by_id(G, node_ids):
    fig, ax = ox.plot_graph(G, show=False, close=False, bgcolor='white', node_size=0, edge_linewidth=0.5, edge_color='#999999')
    x_coords = []
    y_coords = []
    for nid in node_ids:
        x_coords.append(G.nodes[nid]['x'])
        y_coords.append(G.nodes[nid]['y'])

    # Plot all the collected node coordinates on the same axes
    plt.scatter(x_coords, y_coords, c='blue')
    plt.show()
plot_nodes_by_id(G, [val['graph_node'] for val in graph.values()])

graph

init_edges = {}
def apply_closure(G, edge_u, edge_v):
    if G.has_edge(edge_u, edge_v):
        for key in G[edge_u][edge_v]:
            length = EDGES.loc[(edge_u,edge_v)]["length"].values[0]
            if (edge_u, edge_v) not in init_edges:
                init_edges[(edge_u, edge_v)] = length
            G[edge_u][edge_v][key]['length'] = 99999999
    else:
        G.add_edge(edge_u, edge_v, length=99999999)

def lift_closure(G, edge_u, edge_v):
    if (edge_u, edge_v) in init_edges:
        original_length = init_edges[(edge_u, edge_v)]
        if G.has_edge(edge_u, edge_v):
            for key in G[edge_u][edge_v]:
                G[edge_u][edge_v][key]['length'] = original_length
        else:
            G.add_edge(edge_u, edge_v, length=original_length)

ox.save_graphml(G, "udupi_graph.graphml")

def plot_sim(G, node_ids, closed_edges=None, timestep=None, event_desc=None):
    if closed_edges is None:
        closed_edges = set()

    fig, ax = ox.plot_graph(
        G, show=False, close=False,
        bgcolor='white', node_size=0,
        edge_linewidth=0.5, edge_color='#999999'
    )

    for (u, v) in closed_edges:
        if G.has_node(u) and G.has_node(v):
            x = [G.nodes[u]['x'], G.nodes[v]['x']]
            y = [G.nodes[u]['y'], G.nodes[v]['y']]
            ax.plot(x, y, color='red', linewidth=2.5, zorder=3)

    x_coords = [G.nodes[nid]['x'] for nid in node_ids]
    y_coords = [G.nodes[nid]['y'] for nid in node_ids]
    ax.scatter(x_coords, y_coords, c='blue', s=60, zorder=5)

    for i, nid in enumerate(node_ids):
        ax.annotate(
            str(i + 1),
            (G.nodes[nid]['x'], G.nodes[nid]['y']),
            fontsize=7, color='darkblue', zorder=6,
            xytext=(4, 4), textcoords='offset points'
        )

    open_patch   = mpatches.Patch(color='#999999', label='Open edge')
    closed_patch = mpatches.Patch(color='red',     label='Closed edge')
    node_patch   = mpatches.Patch(color='blue',    label='Simulation node')
    ax.legend(handles=[open_patch, closed_patch, node_patch], loc='lower left', fontsize=8)

    title = f"Timestep {timestep}" if timestep is not None else "Road Graph"
    if event_desc:
        title += f" — {event_desc}"
    ax.set_title(title, fontsize=11)

    plt.tight_layout()
    plt.show()

plot_sim(G, [val['graph_node'] for val in graph.values()], timestep=0, event_desc="Initial state")

import time

for current_timestep in range(1, 30):
    with open("/content/closures.json") as f:
        data = json.load(f)

    for event in data["events"]:
        if event["timestep"] != current_timestep:
            continue
        u = event["u"]
        v = event["v"]
        action = event["action"]

        if action == "close":
            apply_closure(G, u, v)
        elif action == "lifted":
            lift_closure(G, u, v)

    edg = []
    for u, v, d in G.edges(data=True):
        edg.append({"u": u, "v": v, "length": d["length"]})

    with open("/content/current_graph.json", "w") as f:
        json.dump({"edges": edg}, f)

    time.sleep(1)

