import json
import os
import networkx as nx
import osmnx as ox

# File paths based on the shared data architecture
DATA_DIR = "data"
DISPATCH_FILE = os.path.join(DATA_DIR, "dispatch_orders.json")
GRAPH_WEIGHTS_FILE = os.path.join(DATA_DIR, "current_graph.json")
VEHICLE_STATES_FILE = os.path.join(DATA_DIR, "vehicle_states.json")
GRAPH_FILE = "udupi_graph.graphml"

class Vehicle:
    def __init__(self, v_id, start_node, v_type):
        self.id = v_id
        self.type = v_type           # NEW: "ambulance" or "truck"
        self.depot = start_node      # NEW: Records the home depot
        self.position = start_node
        self.destination = None
        self.cargo = {}
        self.route = []
        self.status = "idle" 
        self.rerouted = False

    def to_dict(self):
        return {
            "id": self.id,
            "type": self.type,             # Added for Person 4
            "depot": self.depot,           # Added for Person 4
            "position": self.position,
            "status": self.status,
            "destination": self.destination,
            "cargo": self.cargo,
            "route_remaining": self.route,
            "eta_steps": len(self.route),  # NEW: Automatically calculates ETA for the LLM!
            "rerouted": self.rerouted
        }

def haversine_heuristic(node1, node2, G):
    """Calculates the great-circle distance between two nodes for A* heuristic."""
    y1, x1 = G.nodes[node1]['y'], G.nodes[node1]['x']
    y2, x2 = G.nodes[node2]['y'], G.nodes[node2]['x']
    return ox.distance.great_circle(y1, x1, y2, x2)

def load_json(filepath):
    if os.path.exists(filepath):
        with open(filepath, 'r') as f:
            return json.load(f)
    return {}

def save_json(filepath, data):
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=4)

def run_timestep():
    # 1. Load the base graph (assuming Person 2 has generated it)
    if not os.path.exists(GRAPH_FILE):
        print(f"Waiting for {GRAPH_FILE} to be generated by Person 2.")
        return
    try:
        # This will work for Person 2's real integer map nodes later
        G = ox.load_graphml(GRAPH_FILE)
    except ValueError:
        # This acts as our fallback for our dummy string nodes today
        G = nx.read_graphml(GRAPH_FILE, node_type=str)
        
        # We also need to manually convert coordinate strings to floats for the dummy nodes
        for node, data in G.nodes(data=True):
            data['x'] = float(data['x'])
            data['y'] = float(data['y'])
        
    # Force all road weights back to math-ready float numbers!
    for u, v, data in G.edges(data=True):
        if 'weight' in data:
            data['weight'] = float(data['weight'])

    # 2. Apply current edge weights (road closures)
    current_weights = load_json(GRAPH_WEIGHTS_FILE)
    # Assuming current_weights is a dict of edge tuples to weights: {"(u, v)": 999999}
    for edge_str, weight in current_weights.get("weights", {}).items():
        # Parse "(u, v)" back to integers
        u, v = eval(edge_str)
        if G.has_edge(u, v):
            if G.is_multigraph():
                G[u][v][0]['weight'] = float(weight)
            else:
                G[u][v]['weight'] = float(weight)

    # 3. Initialize fleet (Hardcoded as per specs)
    # Note: In a real run, you'd load existing states to persist them across timesteps.
    # For simplicity in this module draft, we establish them here. 
    # (You would typically read vehicle_states.json first if it exists to get current positions).
    fleet = {
        "AMB-01": Vehicle("AMB-01", "DEPOT-A", "ambulance"),
        "AMB-02": Vehicle("AMB-02", "DEPOT-A", "ambulance"),
        "AMB-03": Vehicle("AMB-03", "DEPOT-B", "ambulance"),
        "AMB-04": Vehicle("AMB-04", "DEPOT-C", "ambulance"),
        "AMB-05": Vehicle("AMB-05", "DEPOT-C", "ambulance"),
        "TRUCK-01": Vehicle("TRUCK-01", "DEPOT-A", "truck"),
        "TRUCK-02": Vehicle("TRUCK-02", "DEPOT-B", "truck"),
        "TRUCK-03": Vehicle("TRUCK-03", "DEPOT-C", "truck"),
    }

    # Load existing states to maintain progress across timesteps
    existing_states = load_json(VEHICLE_STATES_FILE)
    if existing_states:
        for v_data in existing_states.get("vehicles", []):
            vid = v_data["id"]
            if vid in fleet:
                fleet[vid].position = v_data["position"]
                fleet[vid].status = v_data["status"]
                fleet[vid].destination = v_data["destination"]
                fleet[vid].cargo = v_data["cargo"]
                fleet[vid].route = v_data["route_remaining"]

    # 4. Check for new dispatch orders
    dispatch_data = load_json(DISPATCH_FILE)
    for order in dispatch_data.get("orders", []):
        vid = order["vehicle_id"]
        if vid in fleet and fleet[vid].status in ["idle", "arrived"]:
            fleet[vid].destination = order["destination"]
            fleet[vid].cargo = order["cargo"]
            fleet[vid].status = "en_route"
            fleet[vid].route = [] # Clear old route to force recalculation

    # 5. Process vehicle movements
    for vid, vehicle in fleet.items():
        vehicle.rerouted = False 

        if vehicle.status == "en_route" and vehicle.destination:
            # Need a new route if we don't have one
            if not vehicle.route:
                try:
                    vehicle.route = nx.astar_path(
                        G, 
                        source=vehicle.position, 
                        target=vehicle.destination, 
                        heuristic=lambda u, v: haversine_heuristic(u, v, G), 
                        weight='weight'
                    )
                    # Remove the starting node from the route queue
                    if vehicle.route:
                        vehicle.route.pop(0) 
                except nx.NetworkXNoPath:
                    print(f"Vehicle {vid} cannot find a path to {vehicle.destination}.")
                    continue

            # Check if next step is blocked (weight == 999999)
            if vehicle.route:
                next_node = vehicle.route[0]
                if G.has_edge(vehicle.position, next_node):
                    if G.is_multigraph():
                        edge_weight = G[vehicle.position][next_node][0].get('weight', 1)
                    else:
                        edge_weight = G[vehicle.position][next_node].get('weight', 1)
                        
                    if float(edge_weight) >= 999999: # Road is closed # Road is closed
                        vehicle.rerouted = True
                        try:
                            # Recalculate A* from current position
                            vehicle.route = nx.astar_path(
                                G, 
                                source=vehicle.position, 
                                target=vehicle.destination, 
                                heuristic=lambda u, v: haversine_heuristic(u, v, G), 
                                weight='weight'
                            )
                            vehicle.route.pop(0)
                        except nx.NetworkXNoPath:
                            print(f"Vehicle {vid} is trapped due to road closures.")
                            continue
                
                # Advance vehicle one step
                if vehicle.route:
                    vehicle.position = vehicle.route.pop(0)

            # Check if arrived
            if not vehicle.route and vehicle.position == vehicle.destination:
                vehicle.status = "arrived"
                vehicle.cargo = {} # Unload cargo
                vehicle.destination = None

    # 6. Save states for the simulation engine and visualizer
    output_data = {"vehicles": [v.to_dict() for v in fleet.values()]}
    save_json(VEHICLE_STATES_FILE, output_data)
    print("Vehicle states updated successfully.")

if __name__ == "__main__":
    run_timestep()